services:
  directus:
    image: directus/directus:11.6.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./extensions:/directus/extensions
    env_file:
      - .env


      